# Generated by Django 3.0.9 on 2020-08-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviDATA_app', '0002_auto_20200805_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('casos', models.IntegerField()),
                ('recuperados', models.IntegerField()),
                ('obitos', models.IntegerField()),
                ('medmov_casos', models.IntegerField()),
                ('medmov_obitos', models.IntegerField()),
            ],
        ),
    ]
