# Generated by Django 3.1 on 2020-08-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviDATA_app', '0004_auto_20200807_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='casos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='media_movel_casos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='media_movel_obitos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='obitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='recuperados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
