# Generated by Django 3.1 on 2020-08-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoviDATA_app', '0005_auto_20200808_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='image',
        ),
    ]
